spring.application.name=notification-service
server.port=${APPLICATION_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT:5432}/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA:v1_notification_service}
spring.datasource.username=${DATABASE_USER:user}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=${DATABASE_SCHEMA:v1_notification_service}
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.schemas=${DATABASE_SCHEMA:v1_notification_service}
spring.flyway.create-schemas=true

# AWS messaging configuration
aws.ses.sender=noreply@bachelor-project.dmitry-cherkes.com
app.aws.sqs.notification-consume-queue=${SQS_NOTIF_QUEUE_URL}
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.region.static=eu-central-1

# logging
logging.level.root=INFO
logging.level.com.dmitrycherkes.weatherservice=DEBUG
