spring.application.name=notification-service
server.port=8184

spring.datasource.url=jdbc:postgresql://notification-service-db:5432/notification_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=v1_notification_service
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.schemas=v1_notification_service
spring.flyway.create-schemas=true


# App Config
app.aws.sqs.notification-consume-queue=notification-consume-queue
aws.ses.sender=noreply@bachelor-project.dmitry-cherkes.com

# AWS / SQS Config
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.region.static=eu-central-1
spring.cloud.aws.endpoint=${AWS_ENDPOINT:http://localstack:4566}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:test}

logging.level.root=INFO
logging.level.com.dmitrycherkes.notificationservice=TRACE
