# docker-compose for starting whole application
services:
  iam-service-db:
    image: postgres:15-alpine
    container_name: iam-service-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iam_db
    volumes:
      - iam-service-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d iam_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - robust-notification-system-network

  iam-service:
    build:
      context: ./iam-service
      dockerfile: docker/Dockerfile
    container_name: iam-service
    depends_on:
      iam-service-db:
        condition: service_healthy
    env_file:
      - .env
      - ./iam-service/.env
    ports:
      - "8180:8180"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8180/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - robust-notification-system-network


  # subscription service
  subscription-service-db:
    image: postgres:15-alpine
    container_name: subscription-service-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscription_db
    volumes:
      - subscription-service-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d subscription_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - robust-notification-system-network

  subscription-service:
    build:
      context: ./subscription-service
      dockerfile: docker/Dockerfile
    container_name: subscription-service
    depends_on:
      subscription-service-db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    env_file:
      - .env
      - ./subscription-service/.env
    ports:
      - "8181:8181"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8181/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - robust-notification-system-network

  # weather service
  weather-service-db:
    image: postgres:15-alpine
    container_name: weather-service-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_db
    volumes:
      - weather-service-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d weather_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - robust-notification-system-network

  weather-service:
    build:
      context: ./weather-service
      dockerfile: docker/Dockerfile
    container_name: weather-service
    depends_on:
      weather-service-db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    env_file:
      - .env
      - ./weather-service/.env
    ports:
      - "8182:8182"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8182/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - robust-notification-system-network

  # decision service
  decision-service-db:
    image: postgres:15-alpine
    container_name: decision-service-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: decision_db
    volumes:
      - decision-service-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d decision_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - robust-notification-system-network

  decision-service:
    build:
      context: ./decision-service
      dockerfile: docker/Dockerfile
    container_name: decision-service
    depends_on:
      decision-service-db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    env_file:
      - .env
      - ./decision-service/.env
    ports:
      - "8183:8183"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8183/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - robust-notification-system-network

  # notification service
  notification-service-db:
    image: postgres:15-alpine
    container_name: notification-service-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notification_db
    volumes:
      - notification-service-db-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d notification_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - robust-notification-system-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: docker/Dockerfile
    container_name: notification-service
    depends_on:
      notification-service-db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    env_file:
      - .env
      - ./notification-service/.env
    ports:
      - "8184:8184"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8184/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - robust-notification-system-network

  # AWS infra
  localstack:
    image: localstack/localstack:4.13.0
    container_name: aws-infra
    ports:
      - "4566:4566"
    entrypoint: >
      /bin/bash -c "
       chmod +x /etc/localstack/init/ready.d/localstack-init.sh &&
       /usr/local/bin/docker-entrypoint.sh
       "
    environment:
      - SERVICES=sqs,sns,ses
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack-init.sh:/etc/localstack/init/ready.d/localstack-init.sh
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - robust-notification-system-network

  # Frontend web app
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: frontend-app
    depends_on:
      subscription-service:
        condition: service_healthy
      iam-service:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
      - ./frontend/docker/nginx.local.conf:/etc/nginx/conf.d/default.conf
    networks:
      - robust-notification-system-network

volumes:
  iam-service-db-data:
    name: iam-service-db-data
  subscription-service-db-data:
    name: subscription-service-db-data
  weather-service-db-data:
    name: weather-service-db-data
  decision-service-db-data:
    name: decision-service-db-data
  notification-service-db-data:
    name: notification-service-db-data

networks:
  robust-notification-system-network:
    driver: bridge
