
# docker-compose for starting whole application
services:
  iam-service-db:
    image: postgres:15-alpine
    container_name: iam-service-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iam_db
    volumes:
      - iam-service-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d iam_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - robust-notification-system-network

  iam-service:
    build:
      context: ./iam-service
      dockerfile: docker/Dockerfile
    container_name: iam-service
    depends_on:
      iam-service-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://iam-service-db:5432/iam_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8180:8180"
    networks:
      - robust-notification-system-network


  # subscription service
  subscription-service-db:
    image: postgres:15-alpine
    container_name: subscription-service-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscription_db
    volumes:
      - subscription-service-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d subscription_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - robust-notification-system-network

  subscription-service:
    build:
      context: ./subscription-service
      dockerfile: docker/Dockerfile
    container_name: subscription-service
    depends_on:
      subscription-service-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://subscription-service-db:5432/subscription_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8181:8181"
    networks:
      - robust-notification-system-network

volumes:
  iam-service-db-data:
    name: iam-service-db-data
  subscription-service-db-data:
    name: subscription-service-db-data

networks:
  robust-notification-system-network:
    driver: bridge
