spring.application.name=weather-service
server.port=${APPLICATION_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT:5432}/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA:v1_weather_service}
spring.datasource.username=${DATABASE_USER:user}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=${DATABASE_SCHEMA:v1_weather_service}
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.schemas=${DATABASE_SCHEMA:v1_weather_service}
spring.flyway.create-schemas=true

# App Config
app.weather.api-key=${WEATHER_API_KEY:dummy_key}
app.weather.base-url=https://api.openweathermap.org/data/3.0/onecall

# AWS messaging configuration
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.region.static=eu-central-1

app.sqs.decision-queue=${SQS_DECISION_QUEUE_URL}
app.sqs.weather-queue=${SQS_WEATHER_QUEUE_URL}

# Resilience4j
resilience4j.circuitbreaker.instances.weatherApi.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.weatherApi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.weatherApi.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.weatherApi.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.weatherApi.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.weatherApi.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.weatherApi.failureRateThreshold=50

# logging
logging.level.root=INFO
logging.level.com.dmitrycherkes.weatherservice=DEBUG
