spring.application.name=weather-service

server.port=8182

spring.datasource.url=jdbc:postgres://host.docker.internal:5432/weather_service
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=v1_weather_service
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.schemas=v1_weather_service
spring.flyway.create-schemas=true

jwt.secret=eGlkoAI8ndZwcb2zVHOo997+Zy8/0S3XtfAb87HlLgjX8LxfHp/tz2ymRIh2+TjcbofV5zNo47HML8BvxQ7HZg==

# logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
