spring.application.name=weather-service
server.port=8182

spring.datasource.url=jdbc:postgresql://weather-service-db:5432/weather_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=v1_weather_service
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.schemas=v1_weather_service
spring.flyway.create-schemas=true

# App Config
app.weather.api-key=${WEATHER_API_KEY:dummy_key}
app.weather.base-url=https://api.openweathermap.org/data/3.0/onecall

# AWS localstack
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.region.static=eu-central-1
spring.cloud.aws.endpoint=${AWS_ENDPOINT:http://localhost:4566}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:test}

app.sqs.decision-queue=decision-consume-queue
app.sqs.weather-queue=weather-consume-queue

# Resilience4j
resilience4j.circuitbreaker.instances.weatherApi.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.weatherApi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.weatherApi.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.weatherApi.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.weatherApi.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.weatherApi.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.weatherApi.failureRateThreshold=50

# logging
logging.level.root=INFO
logging.level.com.dmitrycherkes.weatherservice=DEBUG
