name: iam-microservice-isolated

# docker-compose for starting only iam microservice
services:
  iam-service-db-isolated:
    image: postgres:15-alpine
    container_name: iam-service-db-isolated
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iam_db
    volumes:
      - iam-service-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d iam_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - iam-service-isolated-network

  iam-service-isolated:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: iam-service-isolated
    depends_on:
      iam-service-db-isolated:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://iam-service-db-isolated:5432/iam_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8180:8180"
    networks:
      - iam-service-isolated-network

volumes:
  iam-service-db-data:
    name: iam-service-db-data

networks:
  iam-service-isolated-network:
    driver: bridge
