spring.application.name=subscription-service
server.port=${APPLICATION_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT:5432}/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA:v1_subscription_service}
spring.datasource.username=${DATABASE_USER:user}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=${DATABASE_SCHEMA:v1_subscription_service}
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.schemas=${DATABASE_SCHEMA:v1_subscription_service}
spring.flyway.create-schemas=true

jwt.secret=${JWT_SECRET:eGlkoAI8ndZwcb2zVHOo997+Zy8/0S3XtfAb87HlLgjX8LxfHp/tz2ymRIh2+TjcbofV5zNo47HML8BvxQ7HZg==}

# AWS configuration
app.aws.sns.subscription-topic-arn=${SNS_SUB_TOPIC_ARN}
app.aws.sqs.subscription-consume-queue=${SQS_SUB_QUEUE_URL}

app.allowedorigins=${ALLOWED_ORIGINS:http:localhost}

# AWS localstack
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.region.static=eu-central-1

# logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.dmytrocherkes.subscriptionservice=TRACE
