spring.application.name=subscription-service
server.port=8181

spring.datasource.url=jdbc:postgresql://localhost:5433/subscription_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# feign client
app.services.iam-service.url=http://localhost:8181

# jpa
spring.jpa.properties.hibernate.default_schema=v1_subscription_service
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.schemas=v1_subscription_service
spring.flyway.create-schemas=true

jwt.secret=eGlkoAI8ndZwcb2zVHOo997+Zy8/0S3XtfAb87HlLgjX8LxfHp/tz2ymRIh2+TjcbofV5zNo47HML8BvxQ7HZg==

# AWS configuration
app.aws.sns.subscription-topic-arn=arn:aws:sns:eu-central-1:000000000000:subscription-produce-topic

spring.cloud.aws.region.static=eu-central-1
spring.cloud.aws.endpoint=http://localhost:4566

# logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.dmytrocherkes.subscriptionservice=TRACE
