spring.application.name=iam-service
server.port=${APPLICATION_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT:5432}/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA:v1_iam_service}
spring.datasource.username=${DATABASE_USER:user}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=${DATABASE_SCHEMA:v1_iam_service}
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.schemas=${DATABASE_SCHEMA:v1_iam_service}
spring.flyway.create-schemas=true

# jwt configuration
jwt.secret=${JWT_SECRET:eGlkoAI8ndZwcb2zVHOo997+Zy8/0S3XtfAb87HlLgjX8LxfHp/tz2ymRIh2+TjcbofV5zNo47HML8BvxQ7HZg==}
jwt.lifetime=3600000
jwt.expiration=103600000

# AWS messaging configuration
app.aws.sns.iam-topic-arn=${SNS_IAM_TOPIC_ARN}
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.region.static=eu-central-1

app.allowedorigins=${ALLOWED_ORIGINS:http:localhost}

#logging level
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG
