spring.application.name=iam-service
server.port=${APPLICATION_PORT:8180}

jwt.secret=eGlkoAI8ndZwcb2zVHOo997+Zy8/0S3XtfAb87HlLgjX8LxfHp/tz2ymRIh2+TjcbofV5zNo47HML8BvxQ7HZg==
jwt.lifetime=3600000
jwt.expiration=103600000

spring.datasource.url=jdbc:postgresql://iam-service-db:5432/iam_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=v1_iam_service
spring.jpa.hibernate.ddl-auto=update

spring.flyway.schemas=v1_iam_service

# AWS messaging configuration
app.aws.sns.iam-topic-arn=arn:aws:sns:eu-central-1:000000000000:iam-produce-topic
spring.cloud.aws.region.static=eu-central-1
spring.cloud.aws.endpoint=http://localstack:4566
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:test}

app.allowedorigins=${ALLOWED_ORIGINS:http:localhost}

#logging level
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG
