spring.application.name=decision-service
server.port=8183

spring.datasource.url=jdbc:postgresql://localhost:5435/decision_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=v1_decision_service
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.schemas=v1_decision_service
spring.flyway.create-schemas=true

app.decision.process-delay-ms=30000

# AWS configuration
app.aws.sns.subscription-topic-arn=arn:aws:sns:eu-central-1:000000000000:subscription-produce-topic

spring.cloud.aws.region.static=eu-central-1
spring.cloud.aws.endpoint=http://localhost:4566

logging.level.root=INFO
logging.level.com.dmitrycherkes.decisionservice=TRACE
