spring.application.name=decision-service
server.port=${APPLICATION_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT:5432}/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA:v1_decision_service}
spring.datasource.username=${DATABASE_USER:user}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=${DATABASE_SCHEMA:v1_decision_service}
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.schemas=${DATABASE_SCHEMA:v1_decision_service}
spring.flyway.create-schemas=true

# AWS messaging configuration
app.sqs.notification-queue=${SQS_NOTIF_QUEUE_URL}
app.aws.sqs.decision-consume-queue=${SQS_DECISION_QUEUE_URL}
app.aws.sqs.subscription-queue=${SQS_SUB_QUEUE_URL}
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.region.static=eu-central-1

# logging
logging.level.root=INFO
logging.level.com.dmitrycherkes.weatherservice=DEBUG
