spring.application.name=decision-service
server.port=8183

spring.datasource.url=jdbc:postgresql://localhost:5435/decision_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=v1_decision_service
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.schemas=v1_decision_service
spring.flyway.create-schemas=true

app.decision.process-delay-ms=30000

# App Config
# produce queue
# todo: add notification queue
app.sqs.notification-queue=notification-queue

app.aws.sqs.subscription-queue-name=decision-consume-queue

# AWS / SQS Config
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.region.static=eu-central-1
spring.cloud.aws.endpoint=${AWS_ENDPOINT:http://localhost:4566}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:test}

logging.level.root=INFO
logging.level.com.dmitrycherkes.decisionservice=TRACE
