spring.application.name=decision-service
server.port=8183

spring.datasource.url=jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT:5432}/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA:v1_decision_service}
spring.datasource.username=${DATABASE_USER:user}
spring.datasource.password=${DATABASE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.properties.hibernate.default_schema=${DATABASE_SCHEMA:v1_decision_service}
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.schemas=${DATABASE_SCHEMA:v1_decision_service}
spring.flyway.create-schemas=true

# App Config
# produce queue
app.sqs.notification-queue=notification-queue

app.aws.sqs.decision-consume-queue=decision-consume-queue
app.aws.sqs.subscription-queue=subscription-consume-queue

# AWS / SQS Config
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.region.static=eu-central-1
spring.cloud.aws.endpoint=${AWS_ENDPOINT:http://localstack:4566}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:test}

# logging
logging.level.root=INFO
logging.level.com.dmitrycherkes.weatherservice=DEBUG
